### ISSUE TITLE
[FEATURE] Use `Response` class for handling Request responses  

### ISSUE THREAD

**Issue by guibranco** [guibranco/pancake#264]
Refactor the **Request** class in the **Pancake** project to utilize the new `Response` class for handling responses. This will standardize the response structure across the library, improving consistency, readability, and maintainability.

---

### 🛠️ Implementation Details  

1. **Integrate `Response` Class**  
   - Replace the current return values of the `Request` class methods with instances of the `Response` class.  
   - Ensure all methods in the `Request` class, such as `get()`, `post()`, `put()`, and `delete()`, return a `Response` object.  

2. **Success Handling**  
   - Wrap successful responses (e.g., HTTP 2xx) using `Response::success()`.  
   - Include the relevant response data and a descriptive success message.  

3. **Error Handling**  
   - Wrap non-successful responses (e.g., HTTP 4xx, 5xx) using `Response::error()`.  
   - Include the HTTP status code, error details, and an appropriate error message.  

4. **Serialization**  
   - Add methods in the `Request` class to return responses as arrays or JSON strings via the `Response` methods (`toArray()` or `toJson()`).  

---

### ✅ Expected Behavior  

1. **Consistent Response Structure**  
   - All methods in the `Request` class return a standardized `Response` object.  

2. **Improved Debugging and Logging**  
   - Error details are clearly encapsulated in the `Response` object.  
   - JSON or array serialization can be used directly for logs or debugging.  

3. **Backward Compatibility**  
   - If necessary, include a transitional method or flag to optionally use raw responses for backward compatibility.  

---

### 📖 Example  

**Current Behavior**  
```php
$request = new Request($url);
$response = $request->get();
if ($response['status'] === 200) {
    // Handle success
} else {
    // Handle error
}
```

**Proposed Behavior**  
```php
$request = new Request($url);
$response = $request->get();

if ($response->isSuccess()) {
    $data = $response->getData();
    echo $response->getMessage();
} else {
    echo "Error {$response->getStatusCode()}: {$response->getMessage()}";
}
```

---

### 📋 Tasks  

- [x] Refactor the `Request` class to use the `Response` class.  
- [x] Update unit tests to validate the new behavior.  
- [x] Ensure error handling is robust for both client-side (HTTP 4xx) and server-side (HTTP 5xx) errors.  

---

### Additional Context  

Using the `Response` class will align the **Pancake** toolkit with modern design principles, providing a predictable and unified way to handle API responses.

**Comment by guibranco** [comment]
Implemented via #290
