### ISSUE TITLE
[FEATURE] Implement `Response` class for handling API responses  

### ISSUE THREAD

**Issue by guibranco** [guibranco/pancake#265]
Add a `Response` class to the **Pancake** project to standardize how responses are handled. This class will encapsulate success and error responses, making it easier to manage and debug API interactions.

---

### 🛠️ Implementation Details  

1. **Class Name**  
   `GuiBranco\Pancake\Response`  

2. **Purpose**  
   - Provide a unified structure for handling API responses.  
   - Include metadata such as success status, data, messages, and HTTP status codes.  
   - Enable serialization of responses to JSON or arrays for easy debugging and logging.  

3. **Attributes**  
   - **`success` (bool)**: Indicates whether the response was successful.  
   - **`data` (mixed)**: Contains the response data.  
   - **`message` (string)**: A message explaining the response.  
   - **`statusCode` (int)**: The HTTP status code for the response.  

4. **Methods**  
   - **`success()`**: Creates a successful response.  
   - **`error()`**: Creates an error response.  
   - **Getters**: Access the `success`, `data`, `message`, and `statusCode` attributes.  
   - **Serialization**: Methods like `toArray()` and `toJson()` for converting the response into a standardized format.  

---

### 📖 Example Usage  

**Creating a Successful Response**  
```php
$response = Response::success(['id' => 1, 'name' => 'Example'], 'Data retrieved successfully.');
echo $response->toJson();
```

**Creating an Error Response**  
```php
$response = Response::error('Resource not found.', 404);
echo $response->toJson();
```

---

### ✅ Proposed Implementation  

```php
<?php

namespace GuiBranco\Pancake;

class Response
{
    private bool $success;
    private mixed $data;
    private string $message;
    private int $statusCode;

    /**
     * Response constructor.
     *
     * @param bool $success Indicates if the request was successful.
     * @param mixed $data The data returned by the response.
     * @param string $message A message associated with the response.
     * @param int $statusCode The HTTP status code for the response.
     */
    private function __construct(bool $success, mixed $data = null, string $message = '', int $statusCode = 200)
    {
        $this->success = $success;
        $this->data = $data;
        $this->message = $message;
        $this->statusCode = $statusCode;
    }

    /**
     * Create a successful response.
     *
     * @param mixed $data The data to include in the response.
     * @param string $message An optional success message.
     * @param int $statusCode An optional HTTP status code (default 200).
     * @return static
     */
    public static function success(mixed $data = null, string $message = 'Operation completed successfully.', int $statusCode = 200): self
    {
        return new self(true, $data, $message, $statusCode);
    }

    /**
     * Create an error response.
     *
     * @param string $message The error message.
     * @param int $statusCode The HTTP status code (default 400).
     * @param mixed $data Optional additional error data.
     * @return static
     */
    public static function error(string $message, int $statusCode = 400, mixed $data = null): self
    {
        return new self(false, $data, $message, $statusCode);
    }

    /**
     * Get whether the response indicates success.
     *
     * @return bool
     */
    public function isSuccess(): bool
    {
        return $this->success;
    }

    /**
     * Get the data from the response.
     *
     * @return mixed
     */
    public function getData(): mixed
    {
        return $this->data;
    }

    /**
     * Get the response message.
     *
     * @return string
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Get the HTTP status code for the response.
     *
     * @return int
     */
    public function getStatusCode(): int
    {
        return $this->statusCode;
    }

    /**
     * Convert the response to an associative array.
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'success' => $this->success,
            'data' => $this->data,
            'message' => $this->message,
            'statusCode' => $this->statusCode,
        ];
    }

    /**
     * Convert the response to a JSON string.
     *
     * @return string
     */
    public function toJson(): string
    {
        return json_encode($this->toArray(), JSON_PRETTY_PRINT);
    }
}
```

---

### 📋 Tasks  

- [ ] Implement the `Response` class in `GuiBranco\Pancake`.  
- [ ] Add unit tests to validate the behavior of `Response`.  
- [ ] Update documentation to include examples and usage guidelines.  

---

### Additional Context  

This `Response` class will improve code readability and maintainability by introducing a consistent way to manage API responses in the **Pancake** toolkit.
